--ASSIGNMENT 5--

--Q1. Arrange the ‘Orders’ dataset in decreasing order of amount
SOLUTION:

SELECT*FROM ORDERS
SELECT*FROM ORDERS ORDER BY AMOUNT DESC

/*Q2. . Create a table with the name ‘Employee_details1’ consisting of these columns: ‘Emp_id’, ‘Emp_name’, ‘Emp_salary’. 
Create another table with the name ‘Employee_details2’ consisting of the same columns as the first table.*/
SOLUTION:

CREATE TABLE EMPLOYEE_DETAILS1
(EMP_ID INT,
EMP_NAME VARCHAR(30),
EMP_SALARY INT)

INSERT INTO EMPLOYEE_DETAILS1 VALUES(1, 'AJAY', 50000)
INSERT INTO EMPLOYEE_DETAILS1 VALUES(2, 'MANISH', 55000)
INSERT INTO EMPLOYEE_DETAILS1 VALUES(3, 'SHIKHA', 60000)
INSERT INTO EMPLOYEE_DETAILS1 VALUES(4, 'ARVIND', 70000)

CREATE TABLE EMPLOYEE_DETAILS2
(EMP_ID INT,
EMP_NAME VARCHAR(30),
EMP_SALARY INT)

INSERT INTO EMPLOYEE_DETAILS2 VALUES(1, 'AJAY', 50000)
INSERT INTO EMPLOYEE_DETAILS2 VALUES(2, 'MANISH', 55000)
INSERT INTO EMPLOYEE_DETAILS2 VALUES(5, 'ABDUL', 90000)
INSERT INTO EMPLOYEE_DETAILS2 VALUES(6, 'KAJOL', 97000)

--Q3. Apply the UNION operators on these two tables
SOLUTION:

SELECT* FROM EMPLOYEE_DETAILS1
SELECT* FROM EMPLOYEE_DETAILS2

SELECT*FROM EMPLOYEE_DETAILS1
UNION
SELECT*FROM EMPLOYEE_DETAILS2

SELECT*FROM EMPLOYEE_DETAILS1
UNION ALL
SELECT*FROM EMPLOYEE_DETAILS2

--Q4. Apply the INTERSECT operator on these two tables
SOLUTION:

SELECT*FROM EMPLOYEE_DETAILS1
INTERSECT
SELECT*FROM EMPLOYEE_DETAILS2

--Q5. Apply the EXCEPT operator on these two tables
SOLUTION:

SELECT*FROM EMPLOYEE_DETAILS1
EXCEPT
SELECT*FROM EMPLOYEE_DETAILS2

SELECT*FROM EMPLOYEE_DETAILS2
EXCEPT
SELECT*FROM EMPLOYEE_DETAILS1




